In [33]:
import torch

A = torch.ones((3,4,5))
for i in range(0,4):
    A[:,i,:]=i+1
B = torch.ones((3,5))
B[:,:] = 2
print(A)
print(B)

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [37]:
import numpy as np
C = torch.zeros((3,4))
print(C)

for j in range(0,4):
    for i in range(0,3):
        C[i,j] = torch.dot(A[i,j,:],B[i,:])

print(C)
print(C.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[10., 20., 30., 40.],
        [10., 20., 30., 40.],
        [10., 20., 30., 40.]])
torch.Size([3, 4])


In [40]:
newB = B.unsqueeze(1) 
print(newB.shape)

oldC = torch.bmm(A, newB.transpose(1, 2))
C = oldC.squeeze()
print(C.shape)
print(C)

torch.Size([3, 1, 5])
torch.Size([3, 4])
tensor([[10., 20., 30., 40.],
        [10., 20., 30., 40.],
        [10., 20., 30., 40.]])


In [41]:
import torch.nn.functional as F

softC = F.softmax(C, dim=1)
print(softC)

tensor([[9.3572e-14, 2.0611e-09, 4.5398e-05, 9.9995e-01],
        [9.3572e-14, 2.0611e-09, 4.5398e-05, 9.9995e-01],
        [9.3572e-14, 2.0611e-09, 4.5398e-05, 9.9995e-01]])


In [55]:
# A and softC
import tensorflow

print(A.shape)
print(softC.shape)
newsoftC = softC.unsqueeze(2)
print(newsoftC.shape)

D = A * newsoftC
print(D.shape)
print(D)

torch.Size([3, 4, 5])
torch.Size([3, 4])
torch.Size([3, 4, 1])
torch.Size([3, 4, 5])
tensor([[[9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14],
         [4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09],
         [1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04],
         [3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00]],

        [[9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14],
         [4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09],
         [1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04],
         [3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00]],

        [[9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14, 9.3572e-14],
         [4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09, 4.1221e-09],
         [1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04, 1.3619e-04],
         [3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00, 3.9998e+00]]])


In [11]:
#entonces

import torch
import torch.nn.functional as F
import numpy as np

Q = torch.tensor([[0.0,0.0,0.0], [1,1,1], [0.2,0.2,0.2], [0.3,0.3,0.3]])
K = torch.tensor([[0.1,0.1,0.1], [0.2,0.2,0.2], [0.3,0.3,0.3], [0.4,0.4,0.4]])
V = torch.tensor([[1,0,0], [0,1,0], [0,0,1], [0,1,1]])

S =torch.mm(Q,K.T)
S=S/np.sqrt(K.shape[1])
S = F.softmax(S, dim = 1)
A = torch.sum(S[:, :, None] * V[None, :, :], dim=1)

print(A.shape)
print('\n',A)

torch.Size([4, 3])

 tensor([[0.2500, 0.5000, 0.5000],
        [0.1892, 0.5432, 0.5857],
        [0.2372, 0.5087, 0.5173],
        [0.2309, 0.5130, 0.5260]])
